name: bindings/c-cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run at 8:00 AM every day
    - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit # Audit network and disk activity

      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0

      - name: Setup gcc, g++, cmake, ninja
        run: sudo apt update && sudo apt install -y gcc g++ cmake ninja-build

      - name: Workaround to ensure that regorus.h is generated
        run: |
          cargo fetch
          cargo build -r --frozen
        working-directory: ./bindings/ffi
        
      - name: Test c binding
        run: |
          mkdir bindings/c/build
          cd bindings/c/build
          cmake -G Ninja ..
          ninja
          ./regorus_test

      - name: Test c-nostd binding
        run: |
          mkdir bindings/c-nostd/build
          cd bindings/c-nostd/build
          cmake -G Ninja ..
          ninja
          ./regorus_test

      - name: Test cpp binding
        run: |
          mkdir bindings/cpp/build
          cd bindings/cpp/build
          cmake -G Ninja ..
          ninja
          ./regorus_test
