name: bindings/wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run at 8:00 AM every day
    - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit # Audit network and disk activity

      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18

      - name: Install wasmlpack
        run: cargo install wasm-pack

      - name: Test wasm binding
        run: |
          cd bindings/wasm
          cargo fetch
          cargo clippy --all-targets --no-deps -- -Dwarnings
          wasm-pack build --target nodejs --release
          # Enable when upstream issue is fixed.
          # https://github.com/microsoft/regorus/issues/371
          # wasm-pack test --release --node
          node test.js
