name: bindings/go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run at 8:00 AM every day
    - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit # Audit network and disk activity

      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0
   
          
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          architecture: x64

      - name: Build ffi
        run: cargo build -r
        working-directory: ./bindings/ffi

      - name: Test go
        run: |
          go mod tidy
          go build
          LD_LIBRARY_PATH=../ffi/target/release ./regorus_test
        working-directory: ./bindings/go
